// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHwuoP98_Fe5DzMGGPCOoiiDphJcQ24E',
    appId: '1:1025992833815:web:f0c3d82d8fe610c5499552',
    messagingSenderId: '1025992833815',
    projectId: 'flags-5fe1d',
    authDomain: 'flags-5fe1d.firebaseapp.com',
    storageBucket: 'flags-5fe1d.appspot.com',
    measurementId: 'G-M0LVBFDVEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmjM4Z09EVHoT5Tj_YS0jCb9hImuDME4',
    appId: '1:1025992833815:android:d9e7320314f61c24499552',
    messagingSenderId: '1025992833815',
    projectId: 'flags-5fe1d',
    storageBucket: 'flags-5fe1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fvj73rdGulV5WpX9PH4qE-W4t3wCnEg',
    appId: '1:1025992833815:ios:67cb5cd4810ebb9f499552',
    messagingSenderId: '1025992833815',
    projectId: 'flags-5fe1d',
    storageBucket: 'flags-5fe1d.appspot.com',
    iosClientId: '1025992833815-sonorqh6pnbtecafsg6mki6ttu4blr6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flagGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fvj73rdGulV5WpX9PH4qE-W4t3wCnEg',
    appId: '1:1025992833815:ios:67cb5cd4810ebb9f499552',
    messagingSenderId: '1025992833815',
    projectId: 'flags-5fe1d',
    storageBucket: 'flags-5fe1d.appspot.com',
    iosClientId: '1025992833815-sonorqh6pnbtecafsg6mki6ttu4blr6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flagGame',
  );
}
